apiVersion: v1
kind: Pod
metadata:
    name: myapp-Pod
    labels:
        app: myapp
spec:
    securityContext:
        runAsUser: 1000
        capabilities:
            add: ["MAC_ADMIN"]
    containers:
    -   name: ubuntu
        image: ubuntu
        command: ["sleep", "3000"]