apiVersion: v1
kind: Pod
metadata:
    name: myapp-Pod
    labels:
        app: myapp
spec:
    containers:
    -   name: ubuntu
        image: ubuntu
        command: ["sleep", "3000"]
        securityContext:
            runAsUser: 1000
            capabilities:
                add: ["MAC_ADMIN"]