apiVersion: v1
kind: Pod
metadata:
    name: myapp-Pod
    labels:
        app: myapp
spec:
    containers:
    -   name: nginx-containers
        image: nginx
    affinity:
        nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                -   matchExpressions:
                    -   key: size
                        operator: NotIn
                        values:
                        - Small