apiVersion: v1
kind: Service
metadata: webapp-svc
spec:
  type: ClusterIP
  selector:
    name: webapp
    type: frontend
  ports:
  - targetPort: 80 #port of pod
    port: 80 #port of service object
