apiVersion: v1
kind: Pod
metadata: myapp
spec:
  containers:
  - name: nginx-container
    image: nginx
  affinity:
    nodeAffinity:
      RequiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: NotIn
            values:
            - small
