apiVersion: v1
kind: Pod
metadata: myapp
spec:
  containers:
  - name: nginx-container
    image: nginx
    env:
    - name: app_color
      valueFrom:
        configMapKeyRef:
          name: app_config
          key: app_color
