apiVersion: v1
kind: Pod
metadata:
    name: myapp-Pod
    labels:
        app: myapp
spec:
    nodeName: node01 #use controlplane for master node
    containers:
    -   name: nginx-containers
        image: nginx