apiVersion: v1
kind: Config

current-context: my-kube-admin@my-kube-playground

clusters:

-   name: my-kube-playground
    cluster:
        certificate-authority: ca.crt #better to mention full path or provide certificate in base64 using certificate-authority-data
        server: https://my-kube-playground:6443

contexts:

-   name: my-kube-admin@my-kube-playground
    context:
        cluster: my-kube-playground
        user: my-kube-admin
        namespace: kube-system #optional


users:
    
-   name: my-kube-admin
    user:
        client-cetificate: admin.crt
        client-key: admin.key