apiVersion: v1
kind: Pod
metadata:
    name: ubuntu-Pod
    labels:
        app: myapp
spec:
    containers:
    -   name: ubuntu
        image: ubuntu
        command: ["sleep"] #EntryPoint
        args: ["5000"]  #cmd