#
#kubectl create -f pod-with-secret.yaml
#
apiVersion: v1
kind: Pod
metadata:
    name: myapp-pod
spec:
    containers:
    -   name: simple-webapp-color
        image: simple-webapp-color
        envFrom:
        -   secretRef:
                name: app-secret
        ports:
        - containerPort: 8080
    