#
#kubectl create -f pod-with-secret.yaml
#
apiVersion: v1
kind: Pod
metadata:
    name: myapp-pod
spec:
    containers:
    -   name: simple-webapp-color
        image: simple-webapp-color
        env:
        -   name: DB_PASSWORD
            valueFrom:
                secretKeyRef:
                    name: app-secret
                    key: DB_PASSWORD

        ports:
        - containerPort: 8080
    