#
#kubectl create -f pod-with-secret.yaml
#
apiVersion: v1
kind: Pod
metadata:
    name: myapp-pod
spec:
    containers:
    -   name: simple-webapp-color
        image: simple-webapp-color
        volumes:
        -   name: app-secret-volume
            secret:
                secretName: app-secret #all secrets would be created as files
        ports:
        - containerPort: 8080
    