apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: my-cont
    image: nginx
    volumeMounts:
    - mountPath: /var/www/html
      name: my-vol
  volumes:
  - name: my-vol
    persistentVolumeClaim:
      claimName: myclaim