apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: google-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard #or pd-ssd (sc-gold)
  replication-type: none # regional-pd (sc-platinum)