apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: default-http-backend
  name: default-http-backend
  namespace: ingress-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-http-backend
  template:
    metadata:
      labels:
        app: default-http-backend
    spec:
      initContainers:
      - image: busybox
        name: busybox
        command: ['sh', '-c', 'echo default > /var/index.html']
        volumeMounts:
        - name: cache-volume
          mountPath: /var
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: cache-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: cache-volume
        emptyDir: {}