apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
    name: jane
spec:
    groups:
    -   system: authenticated
    usages:
    -   digital signature
    -   key encipherment
    -   server auth
    request:
        #req in base64 format
        #cat jane.csr | base64
        