apiVersion: v1
kind: Pod
metadata:
    name: myapp-pod
spec:
    containers:
    -   name: simple-webapp-color
        image: simple-webapp-color
        envFrom:
        -   configMapRef:
                name: app-config
        ports:
        -   containerPort: 8080
    