apiVersion: v1
kind: Pod
metadata:
  name: logging-pod
spec:
  containers:
  - name: sidecar
    image: busybox
    command: ['sh', '-c', 'tail -n+1 /var/log/k8slog/application.log']
    volumeMounts:
    - name: logs
      mountPath: /var/log/k8slog
  - name: application-container
    image: busybox
    command: ['sh', '-c', 'while true; do echo \'application running fine\'  > /var/log/k8slog/application.log ; sleep 1; done']
    volumeMounts:
    - name: logs
      mountPath: /var/log/k8slog
  volumes:
  - name: logs
    emptyDir: {}
