apiVersion: v1
kind: Service
metadata:
  name: default-http-backend
  namespace: app-space
spec:
  clusterIP: 10.102.79.255
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: default-backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}